### ISSUE TITLE
주말에러

### ISSUE THREAD

**Issue by inyukwo1** [inyukwo1/slackbot_boblabs_postech#23]
Traceback (most recent call last):
  File "main.py", line 183, in <module>
    for idx in range(1, 4):
  File "main.py", line 145, in get_rist_menu

  File "/Users/inhyukna/gits/slack_bablabs_postech_bot/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/inhyukna/gits/slack_bablabs_postech_bot/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/inhyukna/gits/slack_bablabs_postech_bot/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/inhyukna/gits/slack_bablabs_postech_bot/venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="mealType"]/li[1]/a"}
  (Session info: headless chrome=71.0.3578.98)
  (Driver info: chromedriver=2.45.615355 (d5698f682d8b2742017df6c81e0bd8e6a3063189),platform=Mac OS X 10.14.2 x86_64)

**Comment by seongyun-ko** [comment]
The bot has to take off during the weekend
You forced him to work

**Comment by inyukwo1** [comment]
이상한소리 마시죠ㅡㅡ
